name: Application-Build and Release

permissions:
  contents: write

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build Application
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
#          - ubuntu-latest
          - windows-latest
#          - macos-latest

    defaults:
      run:
        working-directory: ./atlas-texture-creator-gui

    steps:
      - uses: actions/checkout@v3

      - name: Install OS-dependencies (Linux)
        run: |
          sudo apt install -y qt6-base-dev libxcb-cursor0
        if: matrix.os == 'ubuntu-latest'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.0

      - name: Install dependencies
        run: |
          poetry install

      - name: Run build script
        run: |
          poetry run build

      - name: Set zip-file name (linux)
        run: |
          echo "ZIP_FILE_NAME=atlas-texture-creator-linux.zip" >> $GITHUB_ENV
        if: matrix.os == 'ubuntu-latest'

      - name: Set zip-file name (windows)
        run: |
          echo "ZIP_FILE_NAME=atlas-texture-creator-windows.zip" >> $env:GITHUB_ENV
        if: matrix.os == 'windows-latest'

      - name: Set zip-file name (macos)
        run: |
          echo "ZIP_FILE_NAME=atlas-texture-creator-macos.zip" >> $GITHUB_ENV
        if: matrix.os == 'macos-latest'

      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          # Files or directories to zip, relative to GITHUB_WORKSPACE environmental variable
          files: ./atlas-texture-creator-gui/dist/
          dest: ./${{ env.ZIP_FILE_NAME }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_FILE_NAME }}
