name: Application-Build and Release

on:
  push:
#    tags:
#      - '*'
    branches:
      - ci_deploy

jobs:
  build:
    name: Build Application
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    defaults:
      run:
        working-directory: ./atlas-texture-creator-gui

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.2

      - name: Install dependencies
        run: |
          poetry install

      - name: Run build script
        run: |
          poetry run build

      - name: Set zip-file name (linux)
        run: echo "$ZIP_FILE_NAME=atlas-texture-creator-linux.zip" >> $GITHUB_ENV
        if: matrix.os == 'ubuntu-latest'

      - name: Set zip-file name (windows)
        run: echo "$ZIP_FILE_NAME=atlas-texture-creator-windows.zip" >> $GITHUB_ENV
        if: matrix.os == 'windows-latest'

      - name: Set zip-file name (macos)
        run: echo "$ZIP_FILE_NAME=atlas-texture-creator-macos.zip" >> $GITHUB_ENV
        if: matrix.os == 'macos-latest'

      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: ./dist/atlas-texture-creator/
          dest: $ZIP_FILE_NAME

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./$ZIP_FILE_NAME
